### ISSUE TITLE
Matrices and line breaks

### ISSUE THREAD

**Issue by entrity** [CyberZHG/LaTeXGitHubMarkdown#5]
It appears that matrices are not supported adequately: line breaks do not appear.

For example, `$ begin{bmatrix}a&b\\c&d\end{bmatrix} $` and `$$ \left[\begin{array}{l}a&b\\c&d\end{array}\right] $$` each appear all on one line.

**Comment by CyberZHG** [comment]
Because the generated html is used as input, `\\` in markdown will be transformed to `\` first, which is ambiguous to know whether a new line is needed or a special command in LaTeX is being used. However, if you add a line break `\n` after `\\`, the missing `\` will be added, and in the later release adding a space after `\\` will do the same work (though it is still ambiguous).

```
$ \begin{bmatrix}a&b\\ c&d\end{bmatrix} $
```
$ \begin{bmatrix}a&b\\ c&d\end{bmatrix} $

```
$$ \left[\begin{array}{l}a&b\\
c&d\end{array}\right] $$
```
$$ \left[\begin{array}{l}a&b\\
c&d\end{array}\right] $$

![image](https://user-images.githubusercontent.com/853842/31367719-c0e4b558-adab-11e7-8450-57ab86c25e1d.png)
